language: node_js
dist: trusty
addons:
  apt:
    packages:
      - libnss3
node_js:
- '10'
- '14'
install:
- npm ci
script:
- gulp lint release
env:
- NODE_OPTIONS=--max_old_space_size=4096
before_install:
  # Enable user namespace cloning
  - "sysctl kernel.unprivileged_userns_clone=1"
